[package]
name = "simple_rust_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
cargo-watch = "8.5.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0" 
sqlite = "0.34.0"
